apiVersion: gateway.networking.k8s.io/v1
date: "2026-10-07T05:08:41Z"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.6.3
implementation:
  contact:
  - https://github.com/max3584/rproxy-gateway/issues
  organization: max3584
  project: rproxy-gateway
  url: https://github.com/max3584/rproxy-gateway
  version: v0.4.0-dev
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - HTTPRouteRequestHeaderModifier
    result: failure
    statistics:
      Failed: 1
      Passed: 35
      Skipped: 0
  extended:
    failedTests:
    - HTTPRouteResponseHeaderModifier
    - HTTPRouteRewritePath
    result: failure
    statistics:
      Failed: 2
      Passed: 14
      Skipped: 0
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendTimeout
    - HTTPRouteDestinationPortMatching
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteCORS
    - HTTPRouteHostRewrite
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests failed with 1 test failures. Extended tests failed with 2 test
    failures.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 18
      Skipped: 0
  name: GATEWAY-TCP
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 19
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 4
      Skipped: 0
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayStaticAddresses
    - ListenerSet
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 19
      Skipped: 0
  name: GATEWAY-UDP
  summary: Core tests succeeded.
