#!/bin/bash
# Renders config/ from the Helm chart: the Kustomize bases config/default (managed) and config/fleet,
# and config/crd (docs/DESIGN-v0.4.x.md, B). config/ is not edited by hand; the CI job
# "config (kustomize)" renders it again and fails on any difference. Run it after changing the chart
# (and after a version bump: the images' tags come from the chart).
#   scripts/render-config.sh            # HELM=/path/to/helm to use another helm
set -euo pipefail
cd "$(dirname "$0")/.."
HELM=${HELM:-helm}
NS=rproxy-gateway-system
CHART=charts/rproxy-gateway
GENERATED="# Generated by scripts/render-config.sh from $CHART; do not edit."

# crd: rproxy's CRDs (the chart's crds/, `rproxy-gateway crds`)
mkdir -p config/crd
{ echo "$GENERATED"; grep -v '^# Generated by' "$CHART/crds/rproxy.max3584.net.yaml"; } > config/crd/rproxy.max3584.net.yaml
cat > config/crd/kustomization.yaml << YAML
$GENERATED
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rproxy.max3584.net.yaml
YAML

# base <dir> [helm flags]: the chart rendered with fixed values into <dir>/rproxy-gateway.yaml, except
# the controller's ConfigMap, whose data goes to <dir>/config.env (a configMapGenerator: overlays
# change settings with `behavior: merge`, and a changed ConfigMap gets a new name, rolling the controller)
base() {
  local dir=config/$1
  shift
  mkdir -p "$dir"
  "$HELM" template rproxy-gateway "$CHART" -n "$NS" --set rendered=true "$@" |
    awk -v main="$dir/rproxy-gateway.yaml" -v env="$dir/config.env" -v gen="$GENERATED" '
      function flush() {
        if (doc ~ /# Source: [^\n]*\/templates\/config\.yaml/) {
          n = split(doc, lines, "\n")
          for (i = 1; i <= n; i++) {
            if (match(lines[i], /^  RPROXY_GATEWAY_[A-Z_]+: "/)) {
              kv = lines[i]
              sub(/^  /, "", kv)
              sub(/: "/, "=", kv)
              sub(/"$/, "", kv)
              print kv > env
            }
          }
        } else if (doc ~ /[^ \n]/) {
          printf "---\n%s", doc > main
        }
        doc = ""
      }
      BEGIN { print gen > main; print gen > env }
      /^---/ { flush(); next }
      /^# Source: / { doc = doc $0 "\n"; next }
      { doc = doc $0 "\n" }
      END { flush() }
    '
  # the Source comments say which template a document came from; they are dropped (helm versions differ)
  sed -i '/^# Source: /d' "$dir/rproxy-gateway.yaml"
  cat > "$dir/namespace.yaml" << YAML
$GENERATED
apiVersion: v1
kind: Namespace
metadata:
  name: $NS
YAML
  cat > "$dir/kustomization.yaml" << YAML
$GENERATED
# Overlays: config/samples/. The controller's settings are RPROXY_GATEWAY_* (rproxy-gateway controller
# --help) in config.env: change them with a configMapGenerator of the same name and behavior: merge.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../crd
  - namespace.yaml
  - rproxy-gateway.yaml
configMapGenerator:
  - name: rproxy-gateway-config
    namespace: $NS
    envs: [config.env]
YAML
}

base default
base fleet --set fleet.enabled=true
